// Code generated by tools/gen_go_core.py. DO NOT EDIT.
// Copyright (c) 2026 The SEMQ Group Inc.
// Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.

// Package core is the SEMQ C core, compiled by cgo. Importing it links the
// core into the binary; the semq package calls it through semq.h.
package core

/*
#cgo CFLAGS: -std=c11 -O3 -DNDEBUG -I${SRCDIR} -I${SRCDIR}/core -I${SRCDIR}/include
#cgo linux LDFLAGS: -lm
*/
import "C"
