// Code generated by tools/gen_go_core.py. DO NOT EDIT.
// Copyright (c) 2026 The SEMQ Group Inc.
// Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.

package core

// The SIMD kernels the dispatcher can select on amd64.
import (
	_ "github.com/The-SEMQ-Group/semq/bindings/go/internal/core/avx2"
	_ "github.com/The-SEMQ-Group/semq/bindings/go/internal/core/avx512"
)
