/* Code generated by tools/gen_go_core.py. DO NOT EDIT. */
/*
 * Copyright (c) 2026 The SEMQ Group Inc.
 * Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.
 */
#ifndef SEMQ_BUILD_H
#define SEMQ_BUILD_H

#define SEMQ_CORE_VERSION "1.0.0"

#define SEMQI_STR_(x) #x
#define SEMQI_STR(x) SEMQI_STR_(x)
#if defined(__x86_64__)
#define SEMQI_GO_TARGET "scalar+avx2+avx512.x86_64"
#elif defined(__aarch64__)
#define SEMQI_GO_TARGET "scalar+neon+sve.aarch64"
#else
#define SEMQI_GO_TARGET "scalar"
#endif
#if defined(__clang__)
#define SEMQI_GO_COMPILER "Clang-" SEMQI_STR(__clang_major__) "." SEMQI_STR(__clang_minor__) "." SEMQI_STR(__clang_patchlevel__)
#elif defined(__GNUC__)
#define SEMQI_GO_COMPILER "GNU-" SEMQI_STR(__GNUC__) "." SEMQI_STR(__GNUC_MINOR__) "." SEMQI_STR(__GNUC_PATCHLEVEL__)
#else
#define SEMQI_GO_COMPILER "unknown"
#endif
/* The CMake build ID's shape, with "cgo" where CMake records the commit. */
#define SEMQ_BUILD_ID SEMQ_CORE_VERSION "+cgo." SEMQI_GO_TARGET "." SEMQI_GO_COMPILER

#endif /* SEMQ_BUILD_H */
