// Code generated by tools/gen_go_core.py. DO NOT EDIT.
// Copyright (c) 2026 The SEMQ Group Inc.
// Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.

//go:build arm64

package neon

/*
#cgo CFLAGS: -std=c11 -O3 -DNDEBUG -march=armv8-a+simd -I${SRCDIR}/.. -I${SRCDIR}/../core -I${SRCDIR}/../include
*/
import "C"
