#!/usr/bin/env python3
# Copyright (c) 2026 The SEMQ Group Inc.
# Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.
"""Generate the known answers the core checks when it creates a codec.

The core encodes these rows with the kernel it selected for the host and
compares the bytes with the answers below, so a compiler or a CPU that breaks
determinism is caught on the user's machine, not only in CI. The answers come
from the scalar kernel, the reference every other kernel must match, and they
change only when an operator rule changes.

    python tools/gen_selftest.py           # rewrite src/semq_selftest_vectors.h
    python tools/gen_selftest.py --check   # fail if the header is out of date
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "src" / "semq_selftest_vectors.h"
# (operator, parameter, dimension): both phase layouts (packed nibbles at
# <= 16 sectors, which needs a dimension divisible by 4; one byte above), and
# quant at two bin counts. 38 = 2 x 16 + 6 = 4 x 8 + 6 = 9 x 4 + 2 and
# 44 = 2 x 16 + 12 = 5 x 8 + 4: every SIMD kernel runs its main loop and its
# tail.
CONFIGS = (("orbit", 50, 38), ("phase", 8, 44), ("phase", 32, 38), ("quant", 4, 38), ("quant", 16, 38))


def rows(dim: int) -> np.ndarray:
    """Three unit-norm float32 rows that stress rounding, edges and signs."""
    DIM = dim
    rng = np.random.default_rng(20261004 + dim)
    out = []
    # 1. Generic: Gaussian, normalized.
    x = rng.standard_normal(DIM)
    out.append(x / np.linalg.norm(x))
    # 2. Edges: quant bin edges for 4 and 16 bins at this dimension, with both
    #    signs, and equal pairs on the 45 degree diagonal of the phase plane.
    m = 2.0 / np.sqrt(DIM)
    edges = [m * k / 16.0 for k in (1, 3, 4, 5, 8, 11, 12, 15)]
    y = np.zeros(DIM)
    for i, e in enumerate(edges):
        y[2 * i] = y[2 * i + 1] = e if i % 2 == 0 else -e
    # Scale only the free coordinates, so the edges stay where they are.
    free = rng.uniform(-m, m, DIM - 16)
    y[16:] = free * np.sqrt(1.0 - np.sum(y[:16] ** 2)) / np.linalg.norm(free)
    out.append(y)
    # 3. Concentrated: one large coordinate, many tiny ones of mixed sign,
    #    exact zeros, and values beyond the quant range.
    z = rng.uniform(-1e-3, 1e-3, DIM)
    z[::7] = 0.0
    z[5], z[17] = 0.9, -0.4
    out.append(z / np.linalg.norm(z))
    arr = np.asarray(out, dtype=np.float32)
    assert np.all(np.abs(np.sum(arr.astype(np.float64) ** 2, axis=1) - 1.0) <= 2.0 ** -10)
    return arr


def answer(op: str, p1: int, vectors: np.ndarray) -> tuple[int, bytes]:
    os.environ["SEMQ_FORCE_BACKEND"] = "scalar"
    from semq import Codec, CodecConfig

    codec = Codec(getattr(CodecConfig, op)(vectors.shape[1], p1))
    assert codec.backend == "scalar", codec.backend
    encoding = codec.encode(vectors, ids=list(range(len(vectors))))
    return int(codec.config.bytes_per_vector), np.asarray(encoding.rows).tobytes()


def c_array(values: list[str], per_line: int) -> str:
    lines = [", ".join(values[i:i + per_line]) for i in range(0, len(values), per_line)]
    return "    " + ",\n    ".join(lines)


def render() -> str:
    dims = sorted({dim for _, _, dim in CONFIGS})
    parts = [
        "/*",
        " * Copyright (c) 2026 The SEMQ Group Inc.",
        " * Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.",
        " *",
        " * Generated by tools/gen_selftest.py from the scalar kernel. Do not edit.",
        " */",
        "#ifndef SEMQ_SELFTEST_VECTORS_H",
        "#define SEMQ_SELFTEST_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        "#define SEMQI_KAT_ROWS 3u",
        "",
    ]
    inputs = {}
    for dim in dims:
        vectors = rows(dim)
        inputs[dim] = vectors
        parts += [f"/* Input rows of dimension {dim}, as IEEE 754 binary32 bit patterns. */",
                  f"static const uint32_t SEMQI_KAT_INPUT_{dim}[SEMQI_KAT_ROWS * {dim}u] = {{",
                  c_array([f"0x{b:08x}u" for b in vectors.view(np.uint32).ravel()], 6), "};", ""]
    table = []
    for op, p1, dim in CONFIGS:
        bpv, data = answer(op, p1, inputs[dim])
        name = f"SEMQI_KAT_{op.upper()}_{p1}_{dim}"
        parts += [f"/* {op}({dim}, {p1}): 3 rows of {bpv} bytes. */",
                  f"static const uint8_t {name}[{len(data)}] = {{",
                  c_array([f"0x{b:02x}" for b in data], 12), "};", ""]
        table.append(f"    {{ SEMQ_{op.upper()}, {p1}u, {dim}u, {bpv}u, SEMQI_KAT_INPUT_{dim}, {name} }},")
    parts += [
        "typedef struct {",
        "    uint32_t        op;",
        "    uint32_t        p1;",
        "    uint32_t        dim;",
        "    uint32_t        bytes_per_vector;",
        "    const uint32_t* input;",
        "    const uint8_t*  expected;",
        "} semqi_kat_t;",
        "",
        "static const semqi_kat_t SEMQI_KAT[] = {",
        *table,
        "};",
        "",
        "#endif /* SEMQ_SELFTEST_VECTORS_H */",
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the header is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not HEADER.exists() or HEADER.read_text(encoding="utf-8") != text:
            print(f"{HEADER.relative_to(ROOT)} is out of date; run python tools/gen_selftest.py", file=sys.stderr)
            return 1
        print(f"{HEADER.relative_to(ROOT)} is up to date")
        return 0
    HEADER.write_text(text, encoding="utf-8")
    print(f"wrote {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
