#!/usr/bin/env python3
# Copyright (c) 2026 The SEMQ Group Inc.
# Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.
"""Copy the C core into the Go module, so `go get` builds it with cgo.

cgo compiles only the C files inside a package's own directory, and gives
every file in a package the same flags. The core is therefore copied into
bindings/go/internal/core, with one subpackage per SIMD instruction set so
each kernel gets the flags CMake gives it. Two CMake flags are not allowed
in #cgo directives: -ffp-contract=off, replaced by ISO C11 mode (where GCC
does not contract) plus a pragma for clang, and -mfma, which the AVX2
kernels do not need because they use no FMA intrinsics.

    python tools/gen_go_core.py           # rewrite bindings/go/internal/core
    python tools/gen_go_core.py --check   # fail if the copy is out of date
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "bindings" / "go" / "internal" / "core"
MODULE = "github.com/The-SEMQ-Group/semq/bindings/go"

COMMON_CFLAGS = "-std=c11 -O3 -DNDEBUG"
# Subpackage -> (GOARCH, CMake's per-file flags, sources).
KERNELS = {
    "avx2": ("amd64", "-mavx2", ["src/core/semq_avx2.c", "src/core/semq_quant_avx2.c"]),
    "avx512": ("amd64", "-mavx512f -mavx512bw -mavx512vl",
               ["src/core/semq_avx512.c", "src/core/semq_quant_avx512.c"]),
    "neon": ("arm64", "-march=armv8-a+simd",
             ["src/core/semq_neon.c", "src/core/semq_phase_neon.c", "src/core/semq_quant_neon.c"]),
    "armcrypto": ("arm64", "-march=armv8-a+crypto", ["src/semq_sha256_arm.c"]),
    "sve": ("arm64", "-march=armv8-a+sve", ["src/core/semq_sve.c"]),
}
GO_HEADER = "// Code generated by tools/gen_go_core.py. DO NOT EDIT.\n"
LICENSE = (
    "// Copyright (c) 2026 The SEMQ Group Inc.\n"
    "// Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.\n"
)
# GCC does not contract a*b+c into an FMA in ISO C mode; clang needs the pragma.
C_PRELUDE = (
    "#if defined(__clang__)\n"
    "#pragma STDC FP_CONTRACT OFF\n"
    "#endif\n"
)


def build_header(version: str) -> str:
    """semq_build.h, which CMake generates from src/semq_build.h.in."""
    return f"""/* Code generated by tools/gen_go_core.py. DO NOT EDIT. */
#ifndef SEMQ_BUILD_H
#define SEMQ_BUILD_H

#define SEMQ_CORE_VERSION "{version}"

#define SEMQI_STR_(x) #x
#define SEMQI_STR(x) SEMQI_STR_(x)
#if defined(__x86_64__)
#define SEMQI_GO_TARGET "scalar+avx2+avx512.x86_64"
#elif defined(__aarch64__)
#define SEMQI_GO_TARGET "scalar+neon+sve.aarch64"
#else
#define SEMQI_GO_TARGET "scalar"
#endif
#if defined(__clang__)
#define SEMQI_GO_COMPILER "Clang-" SEMQI_STR(__clang_major__) "." SEMQI_STR(__clang_minor__) "." SEMQI_STR(__clang_patchlevel__)
#elif defined(__GNUC__)
#define SEMQI_GO_COMPILER "GNU-" SEMQI_STR(__GNUC__) "." SEMQI_STR(__GNUC_MINOR__) "." SEMQI_STR(__GNUC_PATCHLEVEL__)
#else
#define SEMQI_GO_COMPILER "unknown"
#endif
/* The CMake build ID's shape, with "cgo" where CMake records the commit. */
#define SEMQ_BUILD_ID SEMQ_CORE_VERSION "+cgo." SEMQI_GO_TARGET "." SEMQI_GO_COMPILER

#endif /* SEMQ_BUILD_H */
"""


# Go reads a file name ending in _<GOOS> or _<GOARCH> as a build constraint,
# so semq_sha256_arm.c would build only for 32-bit ARM.
GO_SUFFIXES = {
    "aix", "android", "darwin", "dragonfly", "freebsd", "hurd", "illumos", "ios", "js", "linux", "nacl",
    "netbsd", "openbsd", "plan9", "solaris", "wasip1", "windows", "zos", "386", "amd64", "amd64p32", "arm",
    "armbe", "arm64", "arm64be", "loong64", "mips", "mipsle", "mips64", "mips64le", "mips64p32",
    "mips64p32le", "ppc", "ppc64", "ppc64le", "riscv", "riscv64", "s390", "s390x", "sparc", "sparc64", "wasm",
}
RENAMES = {"semq_sha256_arm.c": "semq_sha256_armv8.c"}


def go_name(source: str) -> str:
    name = RENAMES.get(Path(source).name, Path(source).name)
    if Path(name).stem.rsplit("_", 1)[-1] in GO_SUFFIXES:
        raise ValueError(f"{source}: Go would treat the suffix as a build constraint; add it to RENAMES")
    return name


def copy_c(source: str) -> str:
    text = (ROOT / source).read_text(encoding="utf-8")
    return f"/* Code generated by tools/gen_go_core.py from {source}. DO NOT EDIT. */\n" + C_PRELUDE + text


def copy_h(source: str) -> str:
    text = (ROOT / source).read_text(encoding="utf-8")
    return f"/* Code generated by tools/gen_go_core.py from {source}. DO NOT EDIT. */\n" + text


def go_file(package: str, body: str, build: str | None = None, doc: str = "") -> str:
    constraint = f"//go:build {build}\n\n" if build else ""
    return GO_HEADER + LICENSE + "\n" + constraint + doc + f"package {package}\n" + body


def render() -> dict[str, str]:
    """Every generated file, keyed by its path relative to DEST."""
    simd = {s for _, _, sources in KERNELS.values() for s in sources}
    files: dict[str, str] = {"include/semq.h": copy_h("include/semq.h")}
    for path in sorted((ROOT / "src").glob("*.h")):
        files[path.name] = copy_h(f"src/{path.name}")
    for path in sorted((ROOT / "src" / "core").glob("*.h")):
        files[f"core/{path.name}"] = copy_h(f"src/core/{path.name}")
    for path in sorted([*(ROOT / "src").glob("*.c"), *(ROOT / "src" / "core").glob("*.c")]):
        source = path.relative_to(ROOT).as_posix()
        if source not in simd:
            files[go_name(source)] = copy_c(source)
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    files["semq_build.h"] = build_header(version)

    files["core.go"] = go_file("core", f"""
/*
#cgo CFLAGS: {COMMON_CFLAGS} -I${{SRCDIR}} -I${{SRCDIR}}/core -I${{SRCDIR}}/include
#cgo linux LDFLAGS: -lm
*/
import "C"
""", doc="// Package core is the SEMQ C core, compiled by cgo. Importing it links the\n"
        "// core into the binary; the semq package calls it through semq.h.\n")
    for arch in ("amd64", "arm64"):
        imports = "".join(f'\t_ "{MODULE}/internal/core/{name}"\n'
                          for name, (goarch, _, _) in sorted(KERNELS.items()) if goarch == arch)
        files[f"kernels_{arch}.go"] = go_file("core", f"\n// The SIMD kernels the dispatcher can select on {arch}.\nimport (\n{imports})\n")
    for name, (goarch, flags, sources) in KERNELS.items():
        for source in sources:
            files[f"{name}/{go_name(source)}"] = copy_c(source)
        files[f"{name}/{name}.go"] = go_file(name, f"""
/*
#cgo CFLAGS: {COMMON_CFLAGS} {flags} -I${{SRCDIR}}/.. -I${{SRCDIR}}/../core -I${{SRCDIR}}/../include
*/
import "C"
""", build=goarch)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the copy is out of date")
    args = parser.parse_args()
    files = render()
    relative = DEST.relative_to(ROOT)
    if args.check:
        present = {p.relative_to(DEST).as_posix() for p in DEST.rglob("*") if p.is_file()} if DEST.exists() else set()
        stale = sorted(p for p, text in files.items()
                       if not (DEST / p).is_file() or (DEST / p).read_text(encoding="utf-8") != text)
        extra = sorted(present - set(files))
        if stale or extra:
            for path in stale + extra:
                print(f"{relative}/{path} is out of date", file=sys.stderr)
            print("run python tools/gen_go_core.py", file=sys.stderr)
            return 1
        print(f"{relative} is up to date")
        return 0
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp) / "core"
        for path, text in files.items():
            target = staging / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
        shutil.rmtree(DEST, ignore_errors=True)
        shutil.copytree(staging, DEST)
    print(f"wrote {relative} ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
