# Copyright (c) 2026 The SEMQ Group Inc.
# Licensed under the PolyForm Noncommercial License 1.0.0. See LICENSE.md for terms.
"""The core's known answers match what the scalar kernel produces today.

src/semq_selftest_vectors.h is generated by tools/gen_selftest.py. An operator
rule change that is not followed by regenerating it would make every codec
fail its self-test, so this checks the header against the rules in CI.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def test_self_test_vectors_are_up_to_date() -> None:
    result = subprocess.run([sys.executable, str(ROOT / "tools/gen_selftest.py"), "--check"],
                            capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
